on:
  pull_request:
    types: [opened, synchronize]

name: PR Check

jobs:
  install-deps:
    if: github.repository == 'phpid-jakarta/phpid-learning'
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install locked dependencies
        run: yarn install --frozen-lockfile

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    if: github.repository == 'phpid-jakarta/phpid-learning'
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Lint files
        run: yarn run lint
        env:
          CI: true

  build:
    if: github.repository == 'phpid-jakarta/phpid-learning'
    name: Check build
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Perform build checking
        run: yarn run build
        env:
          CI: true

  script:
    if: github.repository == 'phpid-jakarta/phpid-learning'
    name: Check scripts
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Perform checking script:toJson
        run: yarn run script:toJson
        env:
          CI: true